#
#   Backend
#

openapi: '3.0.3'

info:
  description:   Backend
  version: 0.1.0
  title:   Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        409:
          description: Email address taken or password incorrect
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /register:
    post:
      description: Register
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        201:
          description: Books Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSuccess'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /item:
    post:
      security:
        - bearerAuth: []
      description: Upload Item
      requestBody:
        description: Request Body
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileImage:
                  type: string
                  format: binary
                name:
                  type: string
                price:
                  type: string
                condition:
                  type: string
              required:
                - name
                - price
                - condition
      responses:
        201:
          description: Books Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemUploadSuccess'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    DummyResponse:
      properties:
        message:
          type: string
      required:
        - message

    Credentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    User:
      type: object
      properties:
        email:
          type: string
          format: email
        accessToken:
          type: string
        userid:
          type: string
      required:
        - email
        - accessToken

    Register:
      type: object
      properties:
        name:
          type: object
          properties:
            first:
              type: string
            last:
              type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - name
        - email
        - password

    RegisterSuccess:
      type: string
      properties:
        firstname:
          type: string

    Item:
      type: object
      properties:
        name:
          type: string
        price:
          type: string
        condition:
          type: string
      required:
        - name
        - price
        - condition

    ItemUploadSuccess:
      type: string
      properties:
        name:
          type: string


  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
